---
galaxy_info:
  author: ninja_fleet
  role_name: phone
  description: Android/Phone specific configurations via ADB.
  company: Ninja Fleet
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: GenericUNIX
      versions:
        - all
  galaxy_tags:
    - system
    - android
dependencies: []
