---
galaxy_info:
  author: ninja_fleet
  role_name: mac
  description: macOS specific configurations and apps.
  company: Ninja Fleet
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: MacOSX
      versions:
        - all
  galaxy_tags:
    - system
    - macos
dependencies: []
