$ANSIBLE_VAULT;1.1;AES256
62623836343262613335303062303864343366396563326134336365633165366239313035663233
3961646631353563383766643365313936353436356439360a356530386361306261653036616365
34383035313731633863623936306335326533633730333834346434353039626235326262653065
3866643664646335350a326331363630626164343066366365313934663466306466366237366565
32656133363861346234643233383363316533366235653235633165393936336538313332366164
64656634653964646133303436333765613762653364343732336233366265363237356464313761
31353861386433316232623032613438333137396233333839313136303265326437636636633663
61386165646664313430643562383631383735353530633938393264336363316163386531323264
61646633363961626264336466353736306231616438306665333666653738663935393861663333
64396265653238386632346264323866613130353965643335333664336535366462623632323631
66633364336639396138323834646537623365316134333766353661363965656332343538333939
66303737623833353033363064313439323065393230326130656366363438636662383366363530
66303635633539343631313838306432366237336334386164343938343737663933333235633234
35326331373766356537326633323634363664333766343333653931336331653138636239316336
35346138633935346133643665343765326235666131363634616539313630653431646631373130
63393431616661386331656464643061353635633663633063363134633036336361656336323631
63626633303332323762343735616165613834663330393434356237333335303261386130313965
31393238303031303936306537373862333031383631366462343139376431643363343165373834
30336339343330306237663262613233323163646235356665323530376432333438663636336637
34326435646430323266
