vault_ansible_password: "{{ lookup('1password', 'Development/LinuxServer/password', field='password') }}"
vault_ssh_key: |
  -----BEGIN OPENSSH PRIVATE KEY-----
  # Your encrypted SSH private key here
  -----END OPENSSH PRIVATE KEY-----

# Add other secrets here (API keys, passwords, etc)
