- name: Reload Caddy
  community.docker.docker_container:
    name: caddy
    state: started
    restart: true

- name: Restart wg-easy
  community.docker.docker_container:
    name: wg-easy
    state: started
    restart: true
