---
galaxy_info:
  author: ninja_fleet
  role_name: workstation
  description: Desktop workstation configurations and VPN setup.
  company: Ninja Fleet
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: MacOSX
      versions:
        - all
  galaxy_tags:
    - system
    - desktop
dependencies: []
