services:
  technitium-dns:
    container_name: technitium-dns
    image: technitium/dns-server:latest
    network_mode: "host"
    environment:
      - DNS_SERVER_DOMAIN=dns.ghepting.com
      - TZ=America/Indianapolis
    volumes:
      - /opt/homelab/services/technitium/config:/etc/dns:rw
    restart: unless-stopped
