---
- name: docker | Install Docker (Arch)
  when: ansible_facts['pkg_mgr'] == 'pacman'
  become: true
  community.general.pacman:
    name:
      - docker
      - docker-compose
    state: present

- name: docker | Install Docker (Debian/Ubuntu)
  when: ansible_facts['pkg_mgr'] == 'apt'
  become: true
  block:
    - name: docker | Install Docker deps
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present
        update_cache: true

    - name: docker | Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: docker | Add Docker repo
      ansible.builtin.apt_repository:
        repo: >-
          deb [arch=amd64] https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}
          {{ ansible_facts['distribution_release'] }} stable
        state: present

    - name: docker | Install Docker packages
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true

- name: docker | Install Docker (Fedora)
  when: ansible_facts['pkg_mgr'] == 'dnf'
  become: true
  block:
    - name: docker | Install dnf-plugins-core
      ansible.builtin.dnf:
        name: dnf-plugins-core
        state: present

    - name: docker | Add Docker repo
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/fedora/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        mode: "0644"

    - name: docker | Install Docker packages
      ansible.builtin.dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

- name: docker | Start Docker service
  when: ansible_facts['service_mgr'] == 'systemd'
  become: true
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: docker | Add user to docker group
  when: ansible_facts['os_family'] != 'Darwin'
  become: true
  ansible.builtin.user:
    name: "{{ admin_username }}"
    groups: docker
    append: true
