- name: Setup apt GPG keys
  ansible.builtin.include_tasks: apt.yml
  when: ansible_facts['pkg_mgr'] == 'apt'
  tags: [common, core, apt]

- name: Install core utilities
  ansible.builtin.include_tasks: core.yml
  tags: [common, core]

- name: Install Docker
  ansible.builtin.include_tasks: docker.yml
  tags: [common, docker]

- name: Install Flatpak
  ansible.builtin.include_tasks: flatpak.yml
  tags: [common, flatpak]

- name: Setup Git
  ansible.builtin.include_tasks: git.yml
  tags: [common, git, shell]

- name: Setup Google Chrome (Native)
  ansible.builtin.include_tasks: chrome.yml
  when: ansible_facts['os_family'] != 'Darwin' and ansible_facts['system'] == 'Linux'
  tags: [common, chrome, apps]
