---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-debian12-ansible:latest
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: "/lib/systemd/systemd"
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        # Avoid issues with missing variables in tests
        admin_username: root
        ansible_user: root
        # Git config variables for common role
        user_full_name: "Molecule Test"
        user_email: "molecule@example.com"
        git_signing_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMpjYYXpXgbe79p+yCNoAt2LGRshNo0/4/H9Q1l0p/p"
verifier:
  name: ansible
