services:
  caddy:
    image: caddy:latest
    container_name: caddy
    network_mode: host
    restart: unless-stopped
    volumes:
      - /opt/homelab/services/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /opt/homelab/services/caddy/data:/data
      - /opt/homelab/services/caddy/config:/config
      - /etc/ssl/ghepting:/etc/ssl/ghepting:ro # Mount your certs read-only
    environment:
      - HOME=/data
